#docker-compose.yml
version: "2"
services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gotcitytimemanager_dev
      PGHOST: database
      PGPORT: 5432
    ports:
      - "4000:4000"
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:11.0
    volumes:
      - /var/library/postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: gotcitytimemanager_dev
      DB_HOST: database
      PGPORT: 5432
